services:
  - type: web
    name: synctunes
    env: node
    buildCommand: |
      apt-get update && apt-get install -y yt-dlp python3
      npm install --include=dev
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
